const FETCHING_AUTHENTICATE = "FETCHING_AUTHENTICATE"
const FAILED_AUTHENTICATE = "FAILED_AUTHENTICATE"
const LOGOUT = "LOGOUT"
const GET_TOKEN = "GET_TOKEN"
const AUTHENTICATE = "AUTHENTICATE"
const NEW_GAME = "NEW_GAME"
const UPDATE_GAME = "UDPATE_GAME"

export {
    FETCHING_AUTHENTICATE, 
    FAILED_AUTHENTICATE,
    LOGOUT,
    GET_TOKEN,
    AUTHENTICATE,
    NEW_GAME,
    UPDATE_GAME
}