const FETCHING_AUTHENTICATE = "FETCHING_AUTHENTICATE"
const FAILED_AUTHENTICATE = "FAILED_AUTHENTICATE"
const LOGOUT = "LOGOUT"
const GET_TOKEN = "GET_TOKEN"
const AUTHENTICATE = "AUTHENTICATE"
const LOADING_NEW_GAME = 'LOADING_NEW_GAME  '
const NEW_GAME = "NEW_GAME"
const LOADING_END_GAME_TURN = "LOADING_END_GAME_TURN        "
const END_GAME_TURN = "END_GAME_TURN"
const LOADING_TANK_HIT = "LOADING_TANK_HIT"
const REGISTER_TANK_HIT = "REGISTER_TANK_HIT"
const UPDATE_GAME = "UDPATE_GAME"

export {
    FETCHING_AUTHENTICATE, 
    FAILED_AUTHENTICATE,
    LOGOUT,
    GET_TOKEN,
    AUTHENTICATE,
    LOADING_NEW_GAME,
    NEW_GAME,
    LOADING_END_GAME_TURN,
    END_GAME_TURN,
    REGISTER_TANK_HIT,
    LOADING_TANK_HIT,
    UPDATE_GAME
}